language: python
sudo: false
services:
  - elasticsearch
python:
  - "2.7"
addons:
    apt:
        packages:
            - python-pgmagick
            - libgraphicsmagick++1-dev
            - libboost-python-dev
            - python-pgmagick
install:
  - pip install -r requirements.txt 
  - pip install coveralls
# command to run tests
script:
  - coverage run manage.py test
  - coverage report -m
after_script:
  - coveralls --verbose
