version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/vota
permissions:
  - object: /home/ec2-user/vota
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: deploy_scripts/before_install_system.sh
      timeout: 600
      runas: root
    - location: deploy_scripts/before_install_pip_user.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: deploy_scripts/install_python_dependencies.sh
      timeout: 600
      runas: ec2-user
    - location: deploy_scripts/migrate_and_restart.sh
      timeout: 600
      runas: ec2-user
    - location: deploy_scripts/css.sh
      timeout: 600
      runas: ec2-user
